#!/usr/bin/env fish
apk add --no-cache curl build-base rustup

mkdir -p /rustup
mkdir -p /cargo/bin

set -Ux RUSTUP_HOME "/rustup"
set -Ux CARGO_HOME "/cargo"
fish_add_path -UP "$CARGO_HOME/bin"

rustup-init --no-modify-path