# Image
FROM docker.io/library/alpine:latest

# Install the basics
RUN apk add --no-cache \
    bash bash-completion fish \
    git openssh-client curl \
    pfetch-rs

# Install host-spawn
RUN curl -fsSL \
    https://github.com/1player/host-spawn/releases/latest/download/host-spawn-x86_64 \
    -o /usr/local/bin/host-spawn

# copy setup scripts
COPY scripts/* /usr/local/bin/
#RUN chmod +x /usr/local/bin/* #increases container size

# copy configs
COPY configs/greet.fish /etc/fish/conf.d/
    
# Switch to user
#USER root
